In [145]:
import pandas as pd
df = pd.read_csv('/Users/eunji/bigleader/머신러닝/data/tumor.csv')

In [146]:
df

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0      842302         M        17.99         10.38          122.80     1001.0   
1      842517         M        20.57         17.77          132.90     1326.0   
2    84300903         M        19.69         21.25          130.00     1203.0   
3    84348301         M        11.42         20.38           77.58      386.1   
4    84358402         M        20.29         14.34          135.10     1297.0   
..        ...       ...          ...           ...             ...        ...   
564    926424         M        21.56         22.39          142.00     1479.0   
565    926682         M        20.13         28.25          131.20     1261.0   
566    926954         M        16.60         28.08          108.30      858.1   
567    927241         M        20.60         29.33          140.10     1265.0   
568     92751         B         7.76         24.54           47.92      181.0   

     smoothness_mean  compactness_mean  concavity_mean  concave.points_mean  \
0            0.11840           0.27760         0.30010              0.14710   
1            0.08474           0.07864         0.08690              0.07017   
2            0.10960           0.15990         0.19740              0.12790   
3            0.14250           0.28390         0.24140              0.10520   
4            0.10030           0.13280         0.19800              0.10430   
..               ...               ...             ...                  ...   
564          0.11100           0.11590         0.24390              0.13890   
565          0.09780           0.10340         0.14400              0.09791   
566          0.08455           0.10230         0.09251              0.05302   
567          0.11780           0.27700         0.35140              0.15200   
568          0.05263           0.04362         0.00000              0.00000   

     symmetry_mean  fractal_dimension_mean  
0           0.2419                 0.07871  
1           0.1812                 0.05667  
2           0.2069                 0.05999  
3           0.2597                 0.09744  
4           0.1809                 0.05883  
..             ...                     ...  
564         0.1726                 0.05623  
565         0.1752                 0.05533  
566         0.1590                 0.05648  
567         0.2397                 0.07016  
568         0.1587                 0.05884  

[569 rows x 12 columns]

In [147]:
df.columns

Index(['id', 'diagnosis', 'radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave.points_mean', 'symmetry_mean', 'fractal_dimension_mean'],
      dtype='object')

In [148]:
features = ['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave.points_mean', 'symmetry_mean', 'fractal_dimension_mean']
X = df[features]
y = df['diagnosis']
y.replace({'M':1, 'B':0},inplace=True)

In [149]:
# 트레이닝 / 테스트 데이터 분할
from sklearn.model_selection import train_test_split
X_tn, X_te, y_tn, y_te = train_test_split(X,y,random_state=1004,stratify=y)

In [150]:
from sklearn.preprocessing import StandardScaler
std_scale = StandardScaler()
std_scale.fit(X_tn)
X_tn_std = std_scale.transform(X_tn)
X_te_std = std_scale.transform(X_te)

# KNN

In [202]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=20)
clf_knn.fit(X_tn_std, y_tn) # 메인 코드

KNeighborsClassifier(n_neighbors=20)

In [203]:
knn_pred = clf_knn.predict(X_te_std)
print(knn_pred)

[1 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1
 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 0 1 1 0 1 0 1 1 1 1 1 0 0 1 1 0 0 0
 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]


In [204]:
# 정확도(accuracy)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, knn_pred)
print(accuracy)

# 정밀도(precision_score)
from sklearn.metrics import precision_score
precision = precision_score(y_te, knn_pred,average='binary')
print(precision)

# 리콜
from sklearn.metrics import recall_score
recall = recall_score(y_te, knn_pred, average='binary')
print(recall)

# F1 스코어
from sklearn.metrics import f1_score
f1 = f1_score(y_te, knn_pred, average='binary')
print(f1)

0.965034965034965
0.98
0.9245283018867925
0.9514563106796116


In [154]:
# confusion matrix 확인
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, knn_pred)
print(conf_matrix)

[[85  5]
 [ 4 49]]


In [155]:
# 분류 레포트 확인
from sklearn.metrics import classification_report
class_reprot = classification_report(y_te, knn_pred)
print(class_reprot)

              precision    recall  f1-score   support

           0       0.96      0.94      0.95        90
           1       0.91      0.92      0.92        53

    accuracy                           0.94       143
   macro avg       0.93      0.93      0.93       143
weighted avg       0.94      0.94      0.94       143



# 선형회귀

In [156]:
from sklearn.linear_model import LinearRegression
clf_lr = LinearRegression()
clf_lr.fit(X_tn_std, y_tn)

LinearRegression()

In [157]:
# 선형 회귀분석 모형 추정 계수 확인
print(clf_lr.coef_)
print(clf_lr.intercept_)

[ 2.03878494  0.0856188  -1.69872945 -0.30663642  0.03902338  0.05155986
  0.07888009  0.23352669  0.01108871 -0.0132936 ]
0.3732394366197195


In [158]:
# 릿지 회귀분석 (L2 제약식 적용)
from sklearn.linear_model import Ridge
clf_ridge = Ridge(alpha=1)
clf_ridge.fit(X_tn_std, y_tn)

Intel MKL WARNING: Support of Intel(R) Streaming SIMD Extensions 4.2 (Intel(R) SSE4.2) enabled only processors has been deprecated. Intel oneAPI Math Kernel Library 2025.0 will require Intel(R) Advanced Vector Extensions (Intel(R) AVX) instructions.


Ridge(alpha=1)

In [159]:
# 라쏘 회귀분석 (L1 제약식 적용)
from sklearn.linear_model import Lasso
clf_lasso = Lasso(alpha=0.01)
clf_lasso.fit(X_tn_std, y_tn)

Lasso(alpha=0.01)

In [160]:
# 엘라스틱넷
import numpy as np
from sklearn.model_selection import GridSearchCV
from sklearn.linear_model import ElasticNet
clf_elastic = ElasticNet(alpha=0.01, l1_ratio=0.01)
clf_elastic.fit(X_tn_std, y_tn)

ElasticNet(alpha=0.01, l1_ratio=0.01)

In [161]:
# 예측
pred_lr = clf_lr.predict(X_te_std)
pred_ridge = clf_ridge.predict(X_te_std)
pred_lasso = clf_lasso.predict(X_te_std)
pred_elastic = clf_elastic.predict(X_te_std)
print(pred_lr)

[ 0.87971302  0.96184732 -0.12663243  0.23661171  0.51096665  0.04364649
  0.36437939  0.91394144  0.28382268  0.15016107  0.18166764  0.08837676
  0.90508056  0.23772809  0.6513222  -0.34221255  0.15795187  1.0759179
  0.88196365  1.26498449 -0.26589167  0.28719997  0.86247137  0.25325542
 -0.03107195  0.21525891 -0.04955438 -0.09958059  0.87696733  0.42489185
  0.66290127  0.05321003 -0.11460581  1.50652946  0.53999173  0.01254994
  0.71849235  0.08137371  0.01533185  0.16520882  0.11105874  0.70963354
  0.68349865  0.81030285  0.32034855  0.0195741   0.43933805 -0.01366024
  0.77913832  1.01726246  0.07571033 -0.07591431  0.50578382 -0.06743061
  0.19686175  0.45886775  0.95271023 -0.05350089  0.21274836 -0.17286809
  0.44094604  0.1344521   0.53951184  0.6475274   0.04455727  0.95293823
  0.23558601  0.82502069  0.02856764  0.1811473   0.16247272  0.25045666
  0.84105247 -0.20240894  0.1562079   0.21249818  0.78828593  0.77509601
 -0.05229561  1.03257607 -0.19257163  0.28344105  0.

In [162]:
# 모형 평가 - R 제곱값
from sklearn.metrics import r2_score
print(r2_score(y_te, pred_lr))
print(r2_score(y_te, pred_ridge))
print(r2_score(y_te, pred_lasso))
print(r2_score(y_te, pred_elastic))

0.6945533710822469
0.7002971181832365
0.6775280597710492
0.6950105891455107


In [163]:
# 모형 평가 - MSE
from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_te, pred_lr))
print(mean_squared_error(y_te, pred_ridge))
print(mean_squared_error(y_te, pred_lasso))
print(mean_squared_error(y_te, pred_elastic))

0.07124947038670264
0.06990966532671339
0.07522084966952394
0.07114281821976204


# 로지스틱 회귀

In [164]:
from sklearn.linear_model import LogisticRegression
clf_logi_l2 = LogisticRegression(penalty='l2')
clf_logi_l2.fit(X_tn_std, y_tn)

LogisticRegression()

In [165]:
print(clf_logi_l2.coef_)
print(clf_logi_l2.intercept_)

[[ 1.04220143  1.33684526  0.9319957   1.12395267  1.10940541  0.01849902
   0.94163034  1.4203394   0.2886329  -0.48460481]]
[-0.57746745]


In [166]:
# 예측
pred_logistic = clf_logi_l2.predict(X_te_std)
print(pred_logistic)

[1 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1
 0 0 0 0 1 1 1 0 0 0 0 1 1 0 0 1 0 0 0 1 0 0 0 1 0 1 1 0 1 0 1 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 1 1 0 0 0 1 1 0 1 0 1 1 1 1 1 0 0 1 1 1 0 0
 0 1 0 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]


In [167]:
pred_proa = clf_logi_l2.predict_proba(X_te_std)
print(pred_proa)

[[3.93987438e-04 9.99606013e-01]
 [3.84489043e-04 9.99615511e-01]
 [9.99290222e-01 7.09777853e-04]
 [9.68542988e-01 3.14570123e-02]
 [1.74747623e-01 8.25252377e-01]
 [9.91619590e-01 8.38040958e-03]
 [7.76564529e-01 2.23435471e-01]
 [9.11858940e-05 9.99908814e-01]
 [9.50268958e-01 4.97310420e-02]
 [9.76341774e-01 2.36582258e-02]
 [9.89635788e-01 1.03642123e-02]
 [9.92124840e-01 7.87515984e-03]
 [1.53034152e-03 9.98469658e-01]
 [9.66749427e-01 3.32505726e-02]
 [3.38924686e-02 9.66107531e-01]
 [9.99968950e-01 3.10501429e-05]
 [9.82650608e-01 1.73493920e-02]
 [2.23881509e-05 9.99977612e-01]
 [2.24462224e-03 9.97755378e-01]
 [8.28042110e-06 9.99991720e-01]
 [9.99893876e-01 1.06123860e-04]
 [8.42953368e-01 1.57046632e-01]
 [6.94641950e-04 9.99305358e-01]
 [9.01153995e-01 9.88460046e-02]
 [9.96576192e-01 3.42380784e-03]
 [9.79007907e-01 2.09920926e-02]
 [9.98475980e-01 1.52401952e-03]
 [9.99629582e-01 3.70417821e-04]
 [1.78943804e-05 9.99982106e-01]
 [5.95851085e-01 4.04148915e-01]
 [2.182247

In [168]:
# 정확도(accuracy)
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, pred_logistic)
print(accuracy)

# 정밀도(precision_score)
from sklearn.metrics import precision_score
precision = precision_score(y_te, pred_logistic,average='binary')
print(precision)

# 리콜
from sklearn.metrics import recall_score
recall = recall_score(y_te, pred_logistic, average='binary')
print(recall)

# F1 스코어
from sklearn.metrics import f1_score
f1 = f1_score(y_te, pred_logistic, average='binary')
print(f1)

0.958041958041958
0.9272727272727272
0.9622641509433962
0.9444444444444444


In [169]:
# confusion matrix 확인
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, pred_logistic)
print(conf_matrix)

[[86  4]
 [ 2 51]]


In [170]:
# 분류 레포트 확인
from sklearn.metrics import classification_report
class_report = classification_report(y_te, pred_logistic)
print(class_report)

              precision    recall  f1-score   support

           0       0.98      0.96      0.97        90
           1       0.93      0.96      0.94        53

    accuracy                           0.96       143
   macro avg       0.95      0.96      0.96       143
weighted avg       0.96      0.96      0.96       143



# 나이브 베이즈 

In [171]:
from sklearn.naive_bayes import GaussianNB
clf_gnb = GaussianNB()
clf_gnb.fit(X_tn_std, y_tn)

GaussianNB()

In [172]:
# 예측
pred_gnb = clf_gnb.predict(X_te_std)
print(pred_gnb)

[1 1 0 0 1 0 1 1 1 0 0 0 1 0 1 0 0 1 1 1 0 0 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1
 0 0 0 0 1 1 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 0 0 0 1 0
 0 0 1 1 0 1 0 0 0 0 1 0 0 1 0 0 1 0 0 0 1 1 0 1 0 1 1 1 1 1 0 0 1 1 0 0 0
 0 1 1 0 1 1 1 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0]


In [173]:
# 정확도
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, pred_gnb)
print(accuracy)

# 정밀도
from sklearn.metrics import precision_score
precision = precision_score(y_te, pred_gnb, average='binary')
print(precision)

# 리콜
from sklearn.metrics import recall_score
recall = recall_score(y_te, pred_gnb, average='binary')
print(recall)

# f1 스코어
from sklearn.metrics import f1_score
f1 = f1_score(y_te, pred_gnb, average='binary')
print(f1)

0.9300699300699301
0.9056603773584906
0.9056603773584906
0.9056603773584906


In [174]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, pred_gnb)
print(conf_matrix)

[[85  5]
 [ 5 48]]


In [175]:
from sklearn.metrics import classification_report
class_report = classification_report(y_te, pred_gnb)
print(class_report)

              precision    recall  f1-score   support

           0       0.94      0.94      0.94        90
           1       0.91      0.91      0.91        53

    accuracy                           0.93       143
   macro avg       0.93      0.93      0.93       143
weighted avg       0.93      0.93      0.93       143



# 의사결정나무

In [176]:
from sklearn import tree
clf_tree = tree.DecisionTreeClassifier(criterion='entropy',random_state=1004)
clf_tree.fit(X_tn_std,y_tn)

DecisionTreeClassifier(criterion='entropy', random_state=1004)

In [177]:
# 예측
pred_tree = clf_tree.predict(X_te_std)
print(pred_tree)

[1 1 0 0 1 0 0 1 0 0 0 0 1 0 1 0 0 1 1 1 0 1 1 0 0 0 0 0 1 0 1 0 0 1 1 0 1
 0 0 0 0 1 1 1 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 0 1 0 1 0 0 1 1 1 0
 0 0 1 1 0 1 0 0 0 0 1 0 0 1 1 0 1 0 0 1 1 1 0 1 0 1 1 1 1 1 0 0 1 1 0 0 0
 0 1 0 0 1 1 1 0 0 0 0 1 0 1 1 0 0 0 0 0 0 0 0 1 0 1 1 1 1 0 0 0]


In [178]:
# 정확도
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(y_te, pred_tree)
print(accuracy)

# 정밀도
from sklearn.metrics import precision_score
precision = precision_score(y_te, pred_tree, average='binary')
print(precision)

# 리콜
from sklearn.metrics import recall_score
recall = recall_score(y_te, pred_tree, average='binary')
print(recall)

# f1 스코어
from sklearn.metrics import f1_score
f1 = f1_score(y_te, pred_tree, average='binary')
print(f1)

0.9230769230769231
0.85
0.9622641509433962
0.9026548672566371


In [179]:
from sklearn.metrics import confusion_matrix
conf_matrix = confusion_matrix(y_te, pred_tree)
print(conf_matrix)

[[81  9]
 [ 2 51]]


In [180]:
from sklearn.metrics import classification_report
class_report = classification_report(y_te, pred_tree)
print(class_report)

              precision    recall  f1-score   support

           0       0.98      0.90      0.94        90
           1       0.85      0.96      0.90        53

    accuracy                           0.92       143
   macro avg       0.91      0.93      0.92       143
weighted avg       0.93      0.92      0.92       143

