# ML Day 01

$$ \sum_{x=1}^{n}x = 1+2+3+\cdots + 10$$

In [2]:
res = 0
for i in range(1, 11):
    res += i
print(res)

55


In [3]:
res = 0
for i in range(1, 11):
    res = res + 3
print(res)

30


In [4]:
# 제곱합
res = 0
for i in range(1, 6):
    res += i**2
    print(i, res)
print(res)

1 1
2 5
3 14
4 30
5 55
55


$$ \prod_{x=1}^10 x = 1 \times 2 \times 3 \times \cdots \times 10 $$

In [5]:
res = 1
for i in range(1, 11):
    res *= i
    print(i, res)
print(res)

1 1
2 2
3 6
4 24
5 120
6 720
7 5040
8 40320
9 362880
10 3628800
3628800


$$ n! = n \times (n-1) \times (n-2) \times \cdots \times 2 \times 1 $$

In [9]:
def factorial(n):
    res = 1
    for i in range(1, n+1):
        res *= i
    return res

factorial(5)

120

$$ \begin{pmatrix} n \\ x \end{pmatrix} = nCx = \frac{n!}{x!(n-x)!}$$

In [13]:
# 머신러닝에서 피쳐를 다 쓰는 방법이 있고 특정 피쳐만 뽑는 방식이 있는데, 후자의 경우 combinations이 사용된다.
def combinations(n, r):
    return (factorial(n))/(factorial(r)*factorial(n-r))

combinations(4, 2)

6.0

$$ I_A(x) = \begin{cases} 1, & x \in \mathbf{A} \\ 0, & x \notin \mathbf{A} \end{cases}$$

In [14]:
x = 13
if x <10:
    res = 1
else:
    res = 0

res

0

$$ e = \lim_{n \rightarrow \infty} (1+\frac{1}{n})^n $$

$$ e = 2.718.. $$

$$ min(x) \;\; argmin(x) $$

In [18]:
x = [4,2,5,9,3]
print(min(x)) # -> 최솟값
print(x.index(min(x)))# argmin(x) -> 최솟값의 인덱스

2
1


In [19]:
import numpy as np
x = [4,2,5,9,3]
print(np.min(x))
print(np.argmin(x))

2
1


$$ max(x) \;\; argmax(x)$$

In [20]:
import numpy as np
x = [4,2,5,9,3]
print(np.max(x)) # -> 최댓값
print(np.argmax(x)) # argmax(x) -> 최댓값의 인덱스

9
3


----

In [21]:
# Scalar Practice
import numpy as np
import pandas as pd

df = pd.read_csv('./data/house_prices.csv')
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [22]:
df.iloc[2,4]

0.469

In [23]:
df.iloc[3,5]

6.998

In [26]:
df.iloc[2,3] + df.iloc[4,5]

7.147

---

In [27]:
df

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD  TAX  \
0    0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296   
1    0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242   
2    0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242   
3    0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222   
4    0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222   
..       ...   ...    ...   ...    ...    ...   ...     ...  ...  ...   
501  0.06263   0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273   
502  0.04527   0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273   
503  0.06076   0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273   
504  0.10959   0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273   
505  0.04741   0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273   

     PTRATIO       B  LSTAT  MEDV  
0       15.3  396.90   4.98  24.0  
1       17.8  396.90   9.14  21.6  
2       17.8  392.83   4.03  34.7  
3       18.7  394.63   2.94  33.4  
4       18.7  396.90   5.33  36.2  
..       ...     ...    ...   ...  
501     21.0  391.99   9.67  22.4  
502     21.0  396.90   9.08  20.6  
503     21.0  396.90   5.64  23.9  
504     21.0  393.45   6.48  22.0  
505     21.0  396.90   7.88  11.9  

[506 rows x 14 columns]

In [28]:
df['CRIM']

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64

In [29]:
df['NOX']

0      0.538
1      0.469
2      0.469
3      0.458
4      0.458
       ...  
501    0.573
502    0.573
503    0.573
504    0.573
505    0.573
Name: NOX, Length: 506, dtype: float64

In [30]:
df['CRIM']+df['NOX']

0      0.54432
1      0.49631
2      0.49629
3      0.49037
4      0.52705
        ...   
501    0.63563
502    0.61827
503    0.63376
504    0.68259
505    0.62041
Length: 506, dtype: float64

In [31]:
A = np.array([1,2,3,4,5,6,7,8])
print(A)

[1 2 3 4 5 6 7 8]


In [32]:
A1 = A.reshape(8,1)
print(A1)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [34]:
A1.shape

(8, 1)

In [35]:
A4 = A.reshape(-1, 4)
print(A4)

[[1 2 3 4]
 [5 6 7 8]]


In [36]:
A5 = A.reshape(2, -1)
print(A5)

[[1 2 3 4]
 [5 6 7 8]]


In [37]:
A0 = A.reshape(-1)
print(A0)

[1 2 3 4 5 6 7 8]


In [39]:
t = [[1,2,3],[4,5,6],[7,8,9]]
t = np.array(t)
print(t.reshape(-1))

[1 2 3 4 5 6 7 8 9]


In [41]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [42]:
X = df[['CRIM', 'NOX', 'RM', 'AGE', "TAX"]]
X

CRIM    NOX     RM   AGE  TAX
0    0.00632  0.538  6.575  65.2  296
1    0.02731  0.469  6.421  78.9  242
2    0.02729  0.469  7.185  61.1  242
3    0.03237  0.458  6.998  45.8  222
4    0.06905  0.458  7.147  54.2  222
..       ...    ...    ...   ...  ...
501  0.06263  0.573  6.593  69.1  273
502  0.04527  0.573  6.120  76.7  273
503  0.06076  0.573  6.976  91.0  273
504  0.10959  0.573  6.794  89.3  273
505  0.04741  0.573  6.030  80.8  273

[506 rows x 5 columns]

In [43]:
X_t = np.transpose(X)
X_t

0          1          2          3          4          5    \
CRIM    0.00632    0.02731    0.02729    0.03237    0.06905    0.02985   
NOX     0.53800    0.46900    0.46900    0.45800    0.45800    0.45800   
RM      6.57500    6.42100    7.18500    6.99800    7.14700    6.43000   
AGE    65.20000   78.90000   61.10000   45.80000   54.20000   58.70000   
TAX   296.00000  242.00000  242.00000  222.00000  222.00000  222.00000   

            6          7          8          9    ...       496        497  \
CRIM    0.08829    0.14455    0.21124    0.17004  ...    0.2896    0.26838   
NOX     0.52400    0.52400    0.52400    0.52400  ...    0.5850    0.58500   
RM      6.01200    6.17200    5.63100    6.00400  ...    5.3900    5.79400   
AGE    66.60000   96.10000  100.00000   85.90000  ...   72.9000   70.60000   
TAX   311.00000  311.00000  311.00000  311.00000  ...  391.0000  391.00000   

            498        499        500        501        502        503  \
CRIM    0.23912    0.17783    0.22438    0.06263    0.04527    0.06076   
NOX     0.58500    0.58500    0.58500    0.57300    0.57300    0.57300   
RM      6.01900    5.56900    6.02700    6.59300    6.12000    6.97600   
AGE    65.30000   73.50000   79.70000   69.10000   76.70000   91.00000   
TAX   391.00000  391.00000  391.00000  273.00000  273.00000  273.00000   

            504        505  
CRIM    0.10959    0.04741  
NOX     0.57300    0.57300  
RM      6.79400    6.03000  
AGE    89.30000   80.80000  
TAX   273.00000  273.00000  

[5 rows x 506 columns]

In [44]:
X_tt = X.T
X_tt

0          1          2          3          4          5    \
CRIM    0.00632    0.02731    0.02729    0.03237    0.06905    0.02985   
NOX     0.53800    0.46900    0.46900    0.45800    0.45800    0.45800   
RM      6.57500    6.42100    7.18500    6.99800    7.14700    6.43000   
AGE    65.20000   78.90000   61.10000   45.80000   54.20000   58.70000   
TAX   296.00000  242.00000  242.00000  222.00000  222.00000  222.00000   

            6          7          8          9    ...       496        497  \
CRIM    0.08829    0.14455    0.21124    0.17004  ...    0.2896    0.26838   
NOX     0.52400    0.52400    0.52400    0.52400  ...    0.5850    0.58500   
RM      6.01200    6.17200    5.63100    6.00400  ...    5.3900    5.79400   
AGE    66.60000   96.10000  100.00000   85.90000  ...   72.9000   70.60000   
TAX   311.00000  311.00000  311.00000  311.00000  ...  391.0000  391.00000   

            498        499        500        501        502        503  \
CRIM    0.23912    0.17783    0.22438    0.06263    0.04527    0.06076   
NOX     0.58500    0.58500    0.58500    0.57300    0.57300    0.57300   
RM      6.01900    5.56900    6.02700    6.59300    6.12000    6.97600   
AGE    65.30000   73.50000   79.70000   69.10000   76.70000   91.00000   
TAX   391.00000  391.00000  391.00000  273.00000  273.00000  273.00000   

            504        505  
CRIM    0.10959    0.04741  
NOX     0.57300    0.57300  
RM      6.79400    6.03000  
AGE    89.30000   80.80000  
TAX   273.00000  273.00000  

[5 rows x 506 columns]

In [46]:
X_t.dot(X)

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [47]:
X_t@X

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [48]:
X.dot(X.T)

0             1             2             3             4    \
0    91910.560109  76818.750570  75663.213869  68744.418459  69293.078365   
1    76818.750570  64830.659948  63431.145591  57382.769844  58046.487575   
2    75663.213869  63431.145591  62349.054931  56572.876315  57087.187881   
3    68744.418459  57382.769844  56572.876315  51430.822816  51816.586705   
4    69293.078365  58046.487575  57087.187881  51816.586705  52272.934141   
..            ...           ...           ...           ...           ...   
501  85356.977645  71560.594100  70335.651151  63817.182275  64398.606930   
502  85849.387560  72157.196493  70796.612172  64161.951659  64807.145200   
503  86787.375858  73290.963292  71676.492955  64822.882449  65588.324101   
504  86675.339517  73155.666004  71571.316618  64743.750393  65494.886719   
505  86116.115824  72480.108662  71046.475581  64349.101909  65028.722118   

              5             6             7             8             9    \
0    69581.763843  96438.131370  98362.583726  98613.307072  97696.439287   
1    58396.932647  80555.591219  82884.170116  83188.408176  82078.312084   
2    57356.985167  79374.704385  81178.305521  81412.710256  80553.879136   
3    52017.667870  72134.594826  73486.816327  73661.652568  73018.481488   
4    52511.707035  72694.933852  74294.981257  74502.499335  73740.942321   
..            ...           ...           ...           ...           ...   
501  64704.827294  89545.002898  91584.511301  91850.438665  90878.585274   
502  65147.905385  90048.317689  92311.949436  92607.771535  91528.582430   
503  65992.819928  91005.845329  93691.464907  94042.594943  92762.094488   
504  65891.861125  90891.535456  93526.978661  93871.580416  92614.980063   
505  65387.996749  90320.836798  92705.404265  93017.265197  91880.232434   

     ...            496            497            498            499  \
0    ...  120524.835810  120377.531976  120033.451166  120565.132029   
1    ...  100408.701464  100229.824968   99813.098894  100457.187771   
2    ...   99115.199418   98977.571579   98655.357406   99153.142483   
3    ...   90178.816524   90076.303029   89835.136632   90207.545548   
4    ...   90791.990257   90670.216180   90384.562234   90825.781852   
..   ...            ...            ...            ...            ...   
501  ...  111816.279613  111660.011856  111295.263448  111858.912759   
502  ...  112367.765115  112193.826635  111788.692310  112414.875535   
503  ...  113414.853441  113208.370456  112727.638278  113470.695354   
504  ...  113289.956602  113087.309053  112615.544496  113344.740479   
505  ...  112666.170635  112482.765749  112055.881112  112715.724706   

               500           501           502           503           504  \
0    120972.383673  85356.977645  85849.387560  86787.375858  86675.339517   
1    100949.309860  71560.594100  72157.196493  73290.963292  73155.666004   
2     99535.254483  70335.651151  70796.612172  71676.492955  71571.316618   
3     90494.712139  63817.182275  64161.951659  64822.882449  64743.750393   
4     91165.098392  64398.606930  64807.145200  65588.324101  65494.886719   
..             ...           ...           ...           ...           ...   
501  112290.355269  79347.609901  79869.650324  80863.424902  80744.758035   
502  112893.220603  79869.650324  80449.674778  81551.724200  81420.222570   
503  114038.093190  80863.424902  81551.724200  82858.996597  82703.029932   
504  113901.517233  80744.758035  81420.222570  82703.029932  82549.988775   
505  113219.448653  80152.367088  80763.594075  81924.196490  81785.741345   

              505  
0    86116.115824  
1    72480.108662  
2    71046.475581  
3    64349.101909  
4    65028.722118  
..            ...  
501  80152.367088  
502  80763.594075  
503  81924.196490  
504  81785.741345  
505  81094.331477  

[506 rows x 506 columns]

In [49]:
X@X.T

0             1             2             3             4    \
0    91910.560109  76818.750570  75663.213869  68744.418459  69293.078365   
1    76818.750570  64830.659948  63431.145591  57382.769844  58046.487575   
2    75663.213869  63431.145591  62349.054931  56572.876315  57087.187881   
3    68744.418459  57382.769844  56572.876315  51430.822816  51816.586705   
4    69293.078365  58046.487575  57087.187881  51816.586705  52272.934141   
..            ...           ...           ...           ...           ...   
501  85356.977645  71560.594100  70335.651151  63817.182275  64398.606930   
502  85849.387560  72157.196493  70796.612172  64161.951659  64807.145200   
503  86787.375858  73290.963292  71676.492955  64822.882449  65588.324101   
504  86675.339517  73155.666004  71571.316618  64743.750393  65494.886719   
505  86116.115824  72480.108662  71046.475581  64349.101909  65028.722118   

              5             6             7             8             9    \
0    69581.763843  96438.131370  98362.583726  98613.307072  97696.439287   
1    58396.932647  80555.591219  82884.170116  83188.408176  82078.312084   
2    57356.985167  79374.704385  81178.305521  81412.710256  80553.879136   
3    52017.667870  72134.594826  73486.816327  73661.652568  73018.481488   
4    52511.707035  72694.933852  74294.981257  74502.499335  73740.942321   
..            ...           ...           ...           ...           ...   
501  64704.827294  89545.002898  91584.511301  91850.438665  90878.585274   
502  65147.905385  90048.317689  92311.949436  92607.771535  91528.582430   
503  65992.819928  91005.845329  93691.464907  94042.594943  92762.094488   
504  65891.861125  90891.535456  93526.978661  93871.580416  92614.980063   
505  65387.996749  90320.836798  92705.404265  93017.265197  91880.232434   

     ...            496            497            498            499  \
0    ...  120524.835810  120377.531976  120033.451166  120565.132029   
1    ...  100408.701464  100229.824968   99813.098894  100457.187771   
2    ...   99115.199418   98977.571579   98655.357406   99153.142483   
3    ...   90178.816524   90076.303029   89835.136632   90207.545548   
4    ...   90791.990257   90670.216180   90384.562234   90825.781852   
..   ...            ...            ...            ...            ...   
501  ...  111816.279613  111660.011856  111295.263448  111858.912759   
502  ...  112367.765115  112193.826635  111788.692310  112414.875535   
503  ...  113414.853441  113208.370456  112727.638278  113470.695354   
504  ...  113289.956602  113087.309053  112615.544496  113344.740479   
505  ...  112666.170635  112482.765749  112055.881112  112715.724706   

               500           501           502           503           504  \
0    120972.383673  85356.977645  85849.387560  86787.375858  86675.339517   
1    100949.309860  71560.594100  72157.196493  73290.963292  73155.666004   
2     99535.254483  70335.651151  70796.612172  71676.492955  71571.316618   
3     90494.712139  63817.182275  64161.951659  64822.882449  64743.750393   
4     91165.098392  64398.606930  64807.145200  65588.324101  65494.886719   
..             ...           ...           ...           ...           ...   
501  112290.355269  79347.609901  79869.650324  80863.424902  80744.758035   
502  112893.220603  79869.650324  80449.674778  81551.724200  81420.222570   
503  114038.093190  80863.424902  81551.724200  82858.996597  82703.029932   
504  113901.517233  80744.758035  81420.222570  82703.029932  82549.988775   
505  113219.448653  80152.367088  80763.594075  81924.196490  81785.741345   

              505  
0    86116.115824  
1    72480.108662  
2    71046.475581  
3    64349.101909  
4    65028.722118  
..            ...  
501  80152.367088  
502  80763.594075  
503  81924.196490  
504  81785.741345  
505  81094.331477  

[506 rows x 506 columns]

$$ \mathbf{D} = \begin{pmatrix} d_{11}\;\;0\;\;0 \\ 0\;\;d_{12}\;\;0 \\ 0\;\;0\;\;d_{13}\end{pmatrix}

$$\mathbf{I} = \begin{pmatrix} 1\;0\;0 \\ 0\;1\;0 \\ 0\;0\;1 \end{pmatrix}$$

In [50]:
XtX = X_t@X
np.linalg.det(XtX)

7.91431657769047e+21

In [51]:
XtX_inv = np.linalg.inv(XtX)
print(XtX_inv)

[[ 4.07613803e-05  1.32526683e-04  4.76832932e-05 -1.01889386e-06
  -1.10744437e-06]
 [ 1.32526683e-04  3.44301609e-01 -1.30762150e-02 -8.56047279e-04
  -1.21234099e-04]
 [ 4.76832932e-05 -1.30762150e-02  9.05341934e-04  1.73338529e-05
   1.03814433e-06]
 [-1.01889386e-06 -8.56047279e-04  1.73338529e-05  5.35211609e-06
   4.19638894e-09]
 [-1.10744437e-06 -1.21234099e-04  1.03814433e-06  4.19638894e-09
   1.58047038e-07]]


In [52]:
XtX @ XtX_inv

0             1             2             3             4
CRIM  1.000000e+00 -1.027689e-13  3.671098e-15 -3.118838e-16  5.142724e-17
NOX   8.415393e-18  1.000000e+00 -8.682493e-17 -8.569796e-18  1.978801e-18
RM   -2.473017e-16 -1.448581e-13  1.000000e+00  2.958877e-17  3.277662e-17
AGE  -8.680846e-16 -7.116286e-13 -1.567499e-14  1.000000e+00 -3.419363e-17
TAX  -6.383369e-15 -5.038289e-12 -9.469953e-14 -1.691374e-14  1.000000e+00

In [53]:
XtX_inv @ XtX

CRIM           NOX            RM           AGE           TAX
0  1.000000e+00  6.023165e-17  9.342262e-16  8.900684e-15  6.545484e-14
1 -1.360627e-13  1.000000e+00 -1.585486e-13 -2.132485e-12 -1.610274e-11
2  5.191277e-15  2.490276e-16  1.000000e+00  7.372032e-14  6.235647e-13
3  2.088764e-16  1.206406e-17  2.355744e-16  1.000000e+00  1.633410e-14
4  2.367166e-17  1.978801e-18  3.277662e-17  4.098956e-16  1.000000e+00

In [55]:
crim = df['CRIM']
nox = df['NOX']
res = np.inner(crim, nox)
print(crim, nox)
print(res)

0      0.00632
1      0.02731
2      0.02729
3      0.03237
4      0.06905
        ...   
501    0.06263
502    0.04527
503    0.06076
504    0.10959
505    0.04741
Name: CRIM, Length: 506, dtype: float64 0      0.538
1      0.469
2      0.469
3      0.458
4      0.458
       ...  
501    0.573
502    0.573
503    0.573
504    0.573
505    0.573
Name: NOX, Length: 506, dtype: float64
1226.123170231


In [56]:
cov_x = X_t.dot(X)
cov_x

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [57]:
e, v = np.linalg.eig(cov_x)

In [58]:
e

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [59]:
v

array([[ 1.17248568e-02, -4.34541539e-02, -9.89273583e-01,
         1.38967257e-01, -3.78876853e-04],
       [ 1.21545113e-03,  3.97729110e-03,  5.48368537e-03,
         3.74537281e-02, -9.99274663e-01],
       [ 1.28461807e-02,  4.11504926e-02,  1.37240647e-01,
         9.88869506e-01,  3.79962757e-02],
       [ 1.54544362e-01,  9.86199762e-01, -4.66395497e-02,
        -3.66695593e-02,  2.48287726e-03],
       [ 9.87832003e-01, -1.54313263e-01,  1.72471505e-02,
        -8.81831838e-03,  3.51466736e-04]])

In [60]:
u, s, vt = np.linalg.svd(cov_x)

In [61]:
u

array([[-1.17248568e-02,  4.34541539e-02,  9.89273583e-01,
        -1.38967257e-01, -3.78876853e-04],
       [-1.21545113e-03, -3.97729110e-03, -5.48368537e-03,
        -3.74537281e-02, -9.99274663e-01],
       [-1.28461807e-02, -4.11504926e-02, -1.37240647e-01,
        -9.88869506e-01,  3.79962757e-02],
       [-1.54544362e-01, -9.86199762e-01,  4.66395497e-02,
         3.66695593e-02,  2.48287726e-03],
       [-9.87832003e-01,  1.54313263e-01, -1.72471505e-02,
         8.81831838e-03,  3.51466736e-04]])

In [62]:
s

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [63]:
vt

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [ 4.34541539e-02, -3.97729110e-03, -4.11504926e-02,
        -9.86199762e-01,  1.54313263e-01],
       [ 9.89273583e-01, -5.48368537e-03, -1.37240647e-01,
         4.66395497e-02, -1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])

In [65]:
u2, s2, vt2 = np.linalg.svd(X)

In [66]:
u2

array([[-0.03008946,  0.03086023,  0.01712144, ..., -0.00411115,
        -0.00427013, -0.00365704],
       [-0.02499491,  0.06652264,  0.00780423, ..., -0.05447262,
        -0.05387641, -0.05180949],
       [-0.02472231,  0.03790476,  0.0132068 , ..., -0.01726598,
        -0.01167245,  0.01252377],
       ...,
       [-0.02822706,  0.07823426,  0.00788495, ...,  0.99280739,
        -0.00687219, -0.00535758],
       [-0.02820076,  0.07548049,  0.00791964, ..., -0.00689953,
         0.99336613, -0.00536756],
       [-0.02806907,  0.0617432 ,  0.00995976, ..., -0.00551636,
        -0.00549819,  0.99463978]])

In [67]:
s2

array([1.00553387e+04, 6.12306718e+02, 1.73076199e+02, 4.90216487e+01,
       1.70300420e+00])

In [68]:
vt2

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [-4.34541539e-02,  3.97729110e-03,  4.11504926e-02,
         9.86199762e-01, -1.54313263e-01],
       [-9.89273583e-01,  5.48368537e-03,  1.37240647e-01,
        -4.66395497e-02,  1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])

In [69]:
np.square(s2)

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [70]:
s

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [71]:
vt2

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [-4.34541539e-02,  3.97729110e-03,  4.11504926e-02,
         9.86199762e-01, -1.54313263e-01],
       [-9.89273583e-01,  5.48368537e-03,  1.37240647e-01,
        -4.66395497e-02,  1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])