In [12]:
## 가상환경 py_3_10_4
# conda activate py_3_10_4

import numpy as np
import pandas as pd

df = pd.read_csv("./data/house_prices.csv")
df.index
df.columns.values
# df.iloc[2,4]
# df.iloc[3,5]

array(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD',
       'TAX', 'PTRATIO', 'B', 'LSTAT', 'MEDV'], dtype=object)

In [17]:
df['CRIM']+df['NOX']

0      0.561015
1      0.582005
2      0.581985
3      0.587065
4      0.623745
         ...   
501    0.617325
502    0.599965
503    0.615455
504    0.664285
505    0.602105
Name: CRIM, Length: 506, dtype: float64

In [19]:
X = df[['CRIM','NOX','RM','AGE','TAX']]
#### 전치행렬 만들기

X_t = np.transpose(X)
X_t

0          1          2          3          4          5    \
CRIM    0.00632    0.02731    0.02729    0.03237    0.06905    0.02985   
NOX     0.53800    0.46900    0.46900    0.45800    0.45800    0.45800   
RM      6.57500    6.42100    7.18500    6.99800    7.14700    6.43000   
AGE    65.20000   78.90000   61.10000   45.80000   54.20000   58.70000   
TAX   296.00000  242.00000  242.00000  222.00000  222.00000  222.00000   

            6          7          8          9    ...       496        497  \
CRIM    0.08829    0.14455    0.21124    0.17004  ...    0.2896    0.26838   
NOX     0.52400    0.52400    0.52400    0.52400  ...    0.5850    0.58500   
RM      6.01200    6.17200    5.63100    6.00400  ...    5.3900    5.79400   
AGE    66.60000   96.10000  100.00000   85.90000  ...   72.9000   70.60000   
TAX   311.00000  311.00000  311.00000  311.00000  ...  391.0000  391.00000   

            498        499        500        501        502        503  \
CRIM    0.23912    0.17783    0.22438    0.06263    0.04527    0.06076   
NOX     0.58500    0.58500    0.58500    0.57300    0.57300    0.57300   
RM      6.01900    5.56900    6.02700    6.59300    6.12000    6.97600   
AGE    65.30000   73.50000   79.70000   69.10000   76.70000   91.00000   
TAX   391.00000  391.00000  391.00000  273.00000  273.00000  273.00000   

            504        505  
CRIM    0.10959    0.04741  
NOX     0.57300    0.57300  
RM      6.79400    6.03000  
AGE    89.30000   80.80000  
TAX   273.00000  273.00000  

[5 rows x 506 columns]

In [20]:
X_t@X

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [23]:
## 행렬식 구하기
XtX = X_t@X
XtX #대칭행렬

np.linalg.det(XtX) ## 행렬식 구하기. linearalgebra determinant

## 행렬식이 0이면 역행렬을 구할 수 없다.

7.91431657769047e+21

In [25]:
XtX_inv = np.linalg.inv(XtX)
XtX_inv


array([[ 4.07613803e-05,  1.32526683e-04,  4.76832932e-05,
        -1.01889386e-06, -1.10744437e-06],
       [ 1.32526683e-04,  3.44301609e-01, -1.30762150e-02,
        -8.56047279e-04, -1.21234099e-04],
       [ 4.76832932e-05, -1.30762150e-02,  9.05341934e-04,
         1.73338529e-05,  1.03814433e-06],
       [-1.01889386e-06, -8.56047279e-04,  1.73338529e-05,
         5.35211609e-06,  4.19638894e-09],
       [-1.10744437e-06, -1.21234099e-04,  1.03814433e-06,
         4.19638894e-09,  1.58047038e-07]])

In [27]:
XtX@XtX_inv ##곱했을 때 단위행렬이 나오나..

0             1             2             3             4
CRIM  1.000000e+00 -7.643977e-14 -1.381674e-15 -4.241093e-16  5.193812e-17
NOX  -8.856692e-18  1.000000e+00  2.420336e-16  1.163556e-17 -2.476682e-18
RM    1.730192e-16 -4.334970e-15  1.000000e+00 -1.261543e-16 -2.928635e-17
AGE   6.126108e-16 -6.351444e-13  4.884368e-14  1.000000e+00 -2.194000e-16
TAX   2.829222e-15  4.488510e-13  1.467297e-14 -6.681938e-15  1.000000e+00

In [28]:
## 내적 구하기

crim = df['CRIM'] #vector
nox = df['NOX'] #vector

res = np.inner(crim,nox)
print(res) ##내적값 스칼라

1226.123170231


In [29]:
cov_x = X_t.dot(X)
cov_x #고윳값, 고유 벡터 구하기

CRIM            NOX            RM           AGE           TAX
CRIM  4.397034e+04    1226.123170  1.082195e+04  1.685150e+05  1.173073e+06
NOX   1.226123e+03     162.470380  1.751519e+03  2.045220e+04  1.211706e+05
RM    1.082195e+04    1751.519414  2.023460e+04  2.156702e+05  1.280740e+06
AGE   1.685150e+05   20452.201630  2.156702e+05  2.779615e+06  1.537874e+07
TAX   1.173073e+06  121170.623200  1.280740e+06  1.537874e+07  9.867314e+07

In [30]:
e,v = np.linalg.eig(cov_x)
e #고윳값이 큰 순서대로 나온다.

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [31]:
v #고윳값에 맞는 고유 벡터가 나온다.

array([[ 1.17248568e-02, -4.34541539e-02, -9.89273583e-01,
         1.38967257e-01, -3.78876853e-04],
       [ 1.21545113e-03,  3.97729110e-03,  5.48368537e-03,
         3.74537281e-02, -9.99274663e-01],
       [ 1.28461807e-02,  4.11504926e-02,  1.37240647e-01,
         9.88869506e-01,  3.79962757e-02],
       [ 1.54544362e-01,  9.86199762e-01, -4.66395497e-02,
        -3.66695593e-02,  2.48287726e-03],
       [ 9.87832003e-01, -1.54313263e-01,  1.72471505e-02,
        -8.81831838e-03,  3.51466736e-04]])

In [32]:
#특이값 분해
u,s,vt = np.linalg.svd(cov_x)
u

array([[-1.17248568e-02,  4.34541539e-02,  9.89273583e-01,
        -1.38967257e-01, -3.78876853e-04],
       [-1.21545113e-03, -3.97729110e-03, -5.48368537e-03,
        -3.74537281e-02, -9.99274663e-01],
       [-1.28461807e-02, -4.11504926e-02, -1.37240647e-01,
        -9.88869506e-01,  3.79962757e-02],
       [-1.54544362e-01, -9.86199762e-01,  4.66395497e-02,
         3.66695593e-02,  2.48287726e-03],
       [-9.87832003e-01,  1.54313263e-01, -1.72471505e-02,
         8.81831838e-03,  3.51466736e-04]])

In [33]:
s

array([1.01109837e+08, 3.74919516e+05, 2.99553705e+04, 2.40312204e+03,
       2.90022330e+00])

In [34]:
vt

array([[-1.17248568e-02, -1.21545113e-03, -1.28461807e-02,
        -1.54544362e-01, -9.87832003e-01],
       [ 4.34541539e-02, -3.97729110e-03, -4.11504926e-02,
        -9.86199762e-01,  1.54313263e-01],
       [ 9.89273583e-01, -5.48368537e-03, -1.37240647e-01,
         4.66395497e-02, -1.72471505e-02],
       [-1.38967257e-01, -3.74537281e-02, -9.88869506e-01,
         3.66695593e-02,  8.81831838e-03],
       [-3.78876853e-04, -9.99274663e-01,  3.79962757e-02,
         2.48287726e-03,  3.51466736e-04]])