In [136]:
import pandas as pd
import numpy as np

df = pd.read_csv("./data/tumor.csv")
df.describe()

id  radius_mean  texture_mean  perimeter_mean    area_mean  \
count  5.690000e+02   569.000000    569.000000      569.000000   569.000000   
mean   3.037183e+07    14.127292     19.289649       91.969033   654.889104   
std    1.250206e+08     3.524049      4.301036       24.298981   351.914129   
min    8.670000e+03     6.981000      9.710000       43.790000   143.500000   
25%    8.692180e+05    11.700000     16.170000       75.170000   420.300000   
50%    9.060240e+05    13.370000     18.840000       86.240000   551.100000   
75%    8.813129e+06    15.780000     21.800000      104.100000   782.700000   
max    9.113205e+08    28.110000     39.280000      188.500000  2501.000000   

       smoothness_mean  compactness_mean  concavity_mean  concave.points_mean  \
count       569.000000        569.000000      569.000000           569.000000   
mean          0.096360          0.104341        0.088799             0.048919   
std           0.014064          0.052813        0.079720             0.038803   
min           0.052630          0.019380        0.000000             0.000000   
25%           0.086370          0.064920        0.029560             0.020310   
50%           0.095870          0.092630        0.061540             0.033500   
75%           0.105300          0.130400        0.130700             0.074000   
max           0.163400          0.345400        0.426800             0.201200   

       symmetry_mean  fractal_dimension_mean  
count     569.000000              569.000000  
mean        0.181162                0.062798  
std         0.027414                0.007060  
min         0.106000                0.049960  
25%         0.161900                0.057700  
50%         0.179200                0.061540  
75%         0.195700                0.066120  
max         0.304000                0.097440

In [185]:
# for i in df['diagnosis'].unique() :
#     print(df['diagnosis'].count())

print(df["diagnosis"].groupby(df["diagnosis"]).count())
df["diagnosis"].unique()
# print(df.columns)

feature = ['radius_mean', 'texture_mean', 'perimeter_mean',
       'area_mean', 'smoothness_mean', 'compactness_mean', 'concavity_mean',
       'concave.points_mean', 'symmetry_mean', 'fractal_dimension_mean']

X = df[feature]
y = df['diagnosis']

print(np.corrcoef(X))

#회귀분석 위해 y 추가
df["diagnosis_category"] = [0 if i == 'B' else 1 for i in df['diagnosis']]

diagnosis
B    357
M    212
Name: diagnosis, dtype: int64
[[1.         0.9997348  0.99985247 ... 0.99975169 0.99982538 0.984179  ]
 [0.9997348  1.         0.99996466 ... 0.99953791 0.99990988 0.98141087]
 [0.99985247 0.99996466 1.         ... 0.99975481 0.99998275 0.98296805]
 ...
 [0.99975169 0.99953791 0.99975481 ... 1.         0.99985158 0.98679025]
 [0.99982538 0.99990988 0.99998275 ... 0.99985158 1.         0.9838677 ]
 [0.984179   0.98141087 0.98296805 ... 0.98679025 0.9838677  1.        ]]


In [138]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1004)

In [139]:
from sklearn.preprocessing import StandardScaler
std_scaler = StandardScaler()
std_scaler.fit(X_train)

X_train_std = std_scaler.transform(X_train)
X_test_std = std_scaler.transform(X_test)


In [140]:
from sklearn.neighbors import KNeighborsClassifier
clf_knn = KNeighborsClassifier(n_neighbors=4)
clf_knn.fit(X_train_std, y_train)


KNeighborsClassifier(n_neighbors=4)

In [141]:
knn_pred = clf_knn.predict(X_test_std)

from sklearn.metrics import accuracy_score
print(accuracy_score(y_test,knn_pred))

from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_test,knn_pred))

from sklearn.metrics import classification_report
print(classification_report(y_test,knn_pred))

0.9370629370629371
[[78  1]
 [ 8 56]]
              precision    recall  f1-score   support

           B       0.91      0.99      0.95        79
           M       0.98      0.88      0.93        64

    accuracy                           0.94       143
   macro avg       0.94      0.93      0.94       143
weighted avg       0.94      0.94      0.94       143



In [142]:
# y범주형으로 바꿈
y = df["diagnosis_category"]
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1004)

std_scaler = StandardScaler()
std_scaler.fit(X_train)
X_train_std = std_scaler.transform(X_train)
X_test_std = std_scaler.transform(X_test)

from sklearn.linear_model import LinearRegression

clf_lr = LinearRegression()
clf_lr.fit(X_train_std, y_train)

pred_lr = clf_lr.predict(X_test_std)

from sklearn.metrics import mean_squared_error
print(mean_squared_error(y_test,pred_lr))


0.09425394852266848


In [143]:
#lasso, ridge, elasticnet
from sklearn.linear_model import Lasso

clf_lasso = Lasso(alpha=0.01)
clf_lasso.fit(X_train_std,y_train)
pred_lasso = clf_lasso.predict(X_test_std)

print(mean_squared_error(y_test,pred_lasso))

from sklearn.linear_model import Ridge

clf_ridge = Ridge()
clf_ridge.fit(X_train_std,y_train)
pred_ridge = clf_ridge.predict(X_test_std)

print(mean_squared_error(y_test,pred_ridge))

from sklearn.linear_model import ElasticNet

clf_elas = ElasticNet(alpha=0.01,l1_ratio=0.01)
clf_elas.fit(X_train_std,y_train)
pred_elas = clf_elas.predict(X_test_std)

print(mean_squared_error(y_test,pred_elas))


0.1018599639804855
0.09530689749787684
0.09666489860333877


In [178]:
#Logistic
y = df['diagnosis']
X_train, X_test, y_train, y_test = train_test_split(X,y,random_state=1004)

std_scaler = StandardScaler()
std_scaler.fit(X_train)

X_train_std = std_scaler.transform(X_train)
X_test_std = std_scaler.transform(X_test)

from sklearn.linear_model import LogisticRegression

clf_logi = LogisticRegression(penalty='l2')
clf_logi.fit(X_train_std,y_train)

pred_logi = clf_logi.predict(X_test_std)
pred_logi_2 = clf_logi.predict_proba(X_test_std)
print(pred_logi_2) #ㅇㄱㅇ

from sklearn.metrics import recall_score
print(recall_score(y_test,pred_logi,average='macro'))

[[9.98586288e-01 1.41371173e-03]
 [2.32794726e-02 9.76720527e-01]
 [6.26209347e-01 3.73790653e-01]
 [9.95374166e-01 4.62583414e-03]
 [1.29813865e-02 9.87018613e-01]
 [1.85307616e-04 9.99814692e-01]
 [2.46876199e-02 9.75312380e-01]
 [9.83196995e-01 1.68030055e-02]
 [1.24416543e-01 8.75583457e-01]
 [9.99740819e-01 2.59180824e-04]
 [8.09286882e-02 9.19071312e-01]
 [9.80420475e-01 1.95795253e-02]
 [5.94660494e-04 9.99405340e-01]
 [9.64865519e-01 3.51344810e-02]
 [9.98143873e-01 1.85612671e-03]
 [9.93556327e-01 6.44367320e-03]
 [9.86734552e-01 1.32654477e-02]
 [9.93182194e-01 6.81780576e-03]
 [6.64884589e-02 9.33511541e-01]
 [9.90154201e-01 9.84579926e-03]
 [9.92631073e-01 7.36892673e-03]
 [3.32311884e-04 9.99667688e-01]
 [2.24275412e-01 7.75724588e-01]
 [2.46355339e-01 7.53644661e-01]
 [9.21749041e-01 7.82509589e-02]
 [2.09412443e-04 9.99790588e-01]
 [9.95968706e-01 4.03129416e-03]
 [9.99946362e-01 5.36379206e-05]
 [8.75523457e-01 1.24476543e-01]
 [3.30290842e-01 6.69709158e-01]
 [9.765701

In [181]:
from sklearn.naive_bayes import GaussianNB

y = df['diagnosis_category']
X_train, X_test, y_train, y_test = train_test_split(X,y,stratify=y,random_state=1004)

std_scaler = StandardScaler()
std_scaler.fit(X_train)

X_train_std = std_scaler.transform(X_train)
X_test_std = std_scaler.transform(X_test)


clf_nb = GaussianNB()
clf_nb.fit(X_train,y_train)

pred_nb = clf_nb.predict(X_test)

# accu_score = accuracy_score(y_test, pred_nb)
# print(accu_score)

recl_score = recall_score(y_test,pred_nb,average="binary")
print(recl_score)

# conf_matrix = confusion_matrix(y_test,pred_nb)
# print(conf_matrix)

# class_report = classification_report(y_test,pred_nb)
# print(class_report)

0.9056603773584906


In [175]:
from sklearn import tree

clf_tree = tree.DecisionTreeClassifier(criterion="entropy",random_state=1004)
clf_tree.fit(X_train_std,y_train)

pred_tree = clf_tree.predict(X_test_std)
# print(pred_tree)

# -------------------------------> 클래스 값이 이진이면 binary 쓰면 왜 높아짐?
recl_score = recall_score(y_test,pred_tree,average='binary')
print(recl_score)

# conf_matrix = confusion_matrix(y_test, pred_tree)
# print(conf_matrix)

class_report = classification_report(y_test,pred_tree)
print(class_report)

0.9622641509433962
              precision    recall  f1-score   support

           0       0.98      0.90      0.94        90
           1       0.85      0.96      0.90        53

    accuracy                           0.92       143
   macro avg       0.91      0.93      0.92       143
weighted avg       0.93      0.92      0.92       143

